# Use an official MySQL runtime as a parent image
FROM mysql:latest

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD=root

# Create a database and user
ENV MYSQL_DATABASE=UserPass
ENV MYSQL_USER=naja
ENV MYSQL_PASSWORD=boughader

# When container starts, execute the following SQL script
COPY production/First-release/Dockerfiles/init.sql /docker-entrypoint-initdb.d/

